// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Add2
    {

        [JsonProperty("OnDeath")]
        public bool OnDeath { get; set; }

        [JsonProperty("OnImpact")]
        public bool OnImpact { get; set; }
    }

}
