// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Air
    {

        [JsonProperty("Effects")]
        public IList<Effect5> Effects { get; set; }

        [JsonProperty("Contrails")]
        public Contrails Contrails { get; set; }
    }

}
