// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class AltFootprint
    {

        [JsonProperty("OccupancyCaps")]
        public int OccupancyCaps { get; set; }

        [JsonProperty("MinWaterDepth")]
        public double MinWaterDepth { get; set; }

        [JsonProperty("MaxSlope")]
        public double MaxSlope { get; set; }

        [JsonProperty("Flags")]
        public int Flags { get; set; }

        [JsonProperty("SizeX")]
        public int SizeX { get; set; }

        [JsonProperty("SizeZ")]
        public int SizeZ { get; set; }
    }

}
