// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class AntiMissile
    {

        [JsonProperty("RedirectRateOfFire")]
        public int RedirectRateOfFire { get; set; }

        [JsonProperty("Radius")]
        public int Radius { get; set; }

        [JsonProperty("AttachBone")]
        public string AttachBone { get; set; }
    }

}
