// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Audio
    {

        [JsonProperty("TreeFall")]
        public string TreeFall { get; set; }

        [JsonProperty("BurnLoop")]
        public string BurnLoop { get; set; }

        [JsonProperty("BurnStart")]
        public string BurnStart { get; set; }

        [JsonProperty("UISelection")]
        public string UISelection { get; set; }

        [JsonProperty("AmbientMove")]
        public string AmbientMove { get; set; }

        [JsonProperty("Destroyed")]
        public string Destroyed { get; set; }

        [JsonProperty("StopMove")]
        public string StopMove { get; set; }

        [JsonProperty("AirUnitWaterImpact")]
        public string AirUnitWaterImpact { get; set; }

        [JsonProperty("Killed")]
        public string Killed { get; set; }

        [JsonProperty("Landing")]
        public string Landing { get; set; }

        [JsonProperty("Refueling")]
        public string Refueling { get; set; }

        [JsonProperty("Thruster")]
        public string Thruster { get; set; }

        [JsonProperty("StartMove")]
        public string StartMove { get; set; }

        [JsonProperty("ImpactWater")]
        public string ImpactWater { get; set; }

        [JsonProperty("ImpactTerrain")]
        public string ImpactTerrain { get; set; }

        [JsonProperty("Impact")]
        public string Impact { get; set; }

        [JsonProperty("CommanderArrival")]
        public string CommanderArrival { get; set; }

        [JsonProperty("FootFallGenericSeabed")]
        public string FootFallGenericSeabed { get; set; }

        [JsonProperty("TeleportChargingAtDestination")]
        public string TeleportChargingAtDestination { get; set; }

        [JsonProperty("EnhanceEnd")]
        public string EnhanceEnd { get; set; }

        [JsonProperty("TeleportChargingAtUnit")]
        public string TeleportChargingAtUnit { get; set; }

        [JsonProperty("CaptureLoop")]
        public string CaptureLoop { get; set; }

        [JsonProperty("ReclaimLoop")]
        public string ReclaimLoop { get; set; }

        [JsonProperty("ConstructLoop")]
        public string ConstructLoop { get; set; }

        [JsonProperty("StartReclaim")]
        public string StartReclaim { get; set; }

        [JsonProperty("StartCapture")]
        public string StartCapture { get; set; }

        [JsonProperty("EnhanceLoop")]
        public string EnhanceLoop { get; set; }

        [JsonProperty("TeleportOut")]
        public string TeleportOut { get; set; }

        [JsonProperty("TeleportIn")]
        public string TeleportIn { get; set; }

        [JsonProperty("EnhanceFail")]
        public string EnhanceFail { get; set; }

        [JsonProperty("EnhanceStart")]
        public string EnhanceStart { get; set; }

        [JsonProperty("FootFallGeneric")]
        public string FootFallGeneric { get; set; }

        [JsonProperty("Construct")]
        public string Construct { get; set; }

        [JsonProperty("Close")]
        public string Close { get; set; }

        [JsonProperty("DoneBeingBuilt")]
        public string DoneBeingBuilt { get; set; }

        [JsonProperty("Open")]
        public string Open { get; set; }

        [JsonProperty("EnterWater")]
        public string EnterWater { get; set; }

        [JsonProperty("DeathExplosion")]
        public string DeathExplosion { get; set; }

        [JsonProperty("ShieldOn")]
        public string ShieldOn { get; set; }

        [JsonProperty("ShieldOff")]
        public string ShieldOff { get; set; }

        [JsonProperty("ActiveLoop")]
        public string ActiveLoop { get; set; }

        [JsonProperty("NuclearLaunchDetected")]
        public string NuclearLaunchDetected { get; set; }

        [JsonProperty("NukeCharge")]
        public string NukeCharge { get; set; }

        [JsonProperty("ExistLoop")]
        public string ExistLoop { get; set; }

        [JsonProperty("NukeExplosion")]
        public string NukeExplosion { get; set; }

        [JsonProperty("HoverKilledOnWater")]
        public string HoverKilledOnWater { get; set; }

        [JsonProperty("EggOpen")]
        public string EggOpen { get; set; }

        [JsonProperty("EggSink")]
        public string EggSink { get; set; }

        [JsonProperty("Pack")]
        public string Pack { get; set; }

        [JsonProperty("Unpack")]
        public string Unpack { get; set; }

        [JsonProperty("AmbientMoveSub")]
        public string AmbientMoveSub { get; set; }

        [JsonProperty("SurfaceStart")]
        public string SurfaceStart { get; set; }

        [JsonProperty("StopMoveSub")]
        public string StopMoveSub { get; set; }

        [JsonProperty("StartMoveSub")]
        public string StartMoveSub { get; set; }

        [JsonProperty("SubmergeStart")]
        public string SubmergeStart { get; set; }

        [JsonProperty("Unload")]
        public string Unload { get; set; }

        [JsonProperty("Load")]
        public string Load { get; set; }

        [JsonProperty("AmbientMoveLand")]
        public string AmbientMoveLand { get; set; }

        [JsonProperty("AmbientMoveWater")]
        public string AmbientMoveWater { get; set; }

        [JsonProperty("TransitionWater")]
        public string TransitionWater { get; set; }

        [JsonProperty("Activate")]
        public string Activate { get; set; }

        [JsonProperty("LaunchSat")]
        public string LaunchSat { get; set; }

        [JsonProperty("MoveArms")]
        public string MoveArms { get; set; }

        [JsonProperty("Spawn")]
        public string Spawn { get; set; }

        [JsonProperty("ConstructStop")]
        public string ConstructStop { get; set; }

        [JsonProperty("TransitionLand")]
        public string TransitionLand { get; set; }

        [JsonProperty("TakeOff")]
        public string TakeOff { get; set; }

        [JsonProperty("StopMoveLand")]
        public string StopMoveLand { get; set; }

        [JsonProperty("StartMoveLand")]
        public string StartMoveLand { get; set; }

        [JsonProperty("AmphibiousFloatingKilledOnLand")]
        public string AmphibiousFloatingKilledOnLand { get; set; }

        [JsonProperty("StartMoveWater")]
        public string StartMoveWater { get; set; }

        [JsonProperty("StopMoveWater")]
        public string StopMoveWater { get; set; }
    }

}
