// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Audio2
    {

        [JsonProperty("Fire")]
        public string Fire { get; set; }

        [JsonProperty("BarrelStart")]
        public string BarrelStart { get; set; }

        [JsonProperty("BarrelLoop")]
        public string BarrelLoop { get; set; }

        [JsonProperty("MuzzleChargeStart")]
        public string MuzzleChargeStart { get; set; }

        [JsonProperty("BeamStart")]
        public string BeamStart { get; set; }

        [JsonProperty("BeamStop")]
        public string BeamStop { get; set; }

        [JsonProperty("BeamLoop")]
        public string BeamLoop { get; set; }

        [JsonProperty("FireUnderWater")]
        public string FireUnderWater { get; set; }

        [JsonProperty("Open")]
        public string Open { get; set; }

        [JsonProperty("ChargeStart")]
        public string ChargeStart { get; set; }

        [JsonProperty("Unpack")]
        public string Unpack { get; set; }

        [JsonProperty("BarrelStop")]
        public string BarrelStop { get; set; }
    }

}
