// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class BeamExhaust
    {

        [JsonProperty("Bones")]
        public IList<string> Bones { get; set; }

        [JsonProperty("Cruise")]
        public bool Cruise { get; set; }

        [JsonProperty("Idle")]
        public bool Idle { get; set; }

        [JsonProperty("Landed")]
        public bool? Landed { get; set; }
    }

}
