// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class BlinkingLight
    {

        [JsonProperty("BLScale")]
        public double BLScale { get; set; }

        [JsonProperty("BLOffsetY")]
        public double BLOffsetY { get; set; }

        [JsonProperty("BLOffsetX")]
        public double BLOffsetX { get; set; }

        [JsonProperty("BLBone")]
        public object BLBone { get; set; }

        [JsonProperty("BLOffsetZ")]
        public double BLOffsetZ { get; set; }
    }

}
