// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class BlinkingLightsFx
    {

        [JsonProperty("Yellow")]
        public string Yellow { get; set; }

        [JsonProperty("Green")]
        public string Green { get; set; }

        [JsonProperty("Red")]
        public string Red { get; set; }
    }

}
