// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Buff
    {

        [JsonProperty("Radius")]
        public int Radius { get; set; }

        [JsonProperty("AppliedToTarget")]
        public bool AppliedToTarget { get; set; }

        [JsonProperty("Add")]
        public Add Add { get; set; }

        [JsonProperty("BuffType")]
        public string BuffType { get; set; }

        [JsonProperty("Duration")]
        public double Duration { get; set; }

        [JsonProperty("TargetAllow")]
        public string TargetAllow { get; set; }

        [JsonProperty("TargetDisallow")]
        public string TargetDisallow { get; set; }
    }

}
