// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class BuffFields
    {

        [JsonProperty("RegenField")]
        public string RegenField { get; set; }

        [JsonProperty("AdvancedRegenField")]
        public string AdvancedRegenField { get; set; }
    }

}
