// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Buffs
    {

        [JsonProperty("Regen")]
        public Regen Regen { get; set; }

        [JsonProperty("Stun")]
        public Stun Stun { get; set; }
    }

}
