// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class BuildBones
    {

        [JsonProperty("AimBone")]
        public object AimBone { get; set; }

        [JsonProperty("PitchBone")]
        public string PitchBone { get; set; }

        [JsonProperty("YawBone")]
        public string YawBone { get; set; }

        [JsonProperty("BuildEffectBones")]
        public IList<object> BuildEffectBones { get; set; }

        [JsonProperty("BuildAttachBone")]
        public string BuildAttachBone { get; set; }
    }

}
