// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class BuildBonesAlt1
    {

        [JsonProperty("AimBone")]
        public string AimBone { get; set; }

        [JsonProperty("PitchBone")]
        public string PitchBone { get; set; }

        [JsonProperty("YawBone")]
        public string YawBone { get; set; }
    }

}
