// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class CameraShake2
    {

        [JsonProperty("Radius")]
        public int Radius { get; set; }

        [JsonProperty("MinShakeAtRadius")]
        public int MinShakeAtRadius { get; set; }

        [JsonProperty("Interval")]
        public int Interval { get; set; }

        [JsonProperty("MaxShakeEpicenter")]
        public double MaxShakeEpicenter { get; set; }
    }

}
