// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class ChargeFxAtUnitBone
    {

        [JsonProperty("Offset")]
        public IList<double> Offset { get; set; }

        [JsonProperty("Bone")]
        public string Bone { get; set; }
    }

}
