// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Contrails
    {

        [JsonProperty("Bones")]
        public IList<string> Bones { get; set; }

        [JsonProperty("ZOffset")]
        public int? ZOffset { get; set; }
    }

}
