// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class DamageEffect
    {

        [JsonProperty("OffsetX")]
        public double OffsetX { get; set; }

        [JsonProperty("Bone")]
        public object Bone { get; set; }

        [JsonProperty("OffsetY")]
        public double OffsetY { get; set; }

        [JsonProperty("OffsetZ")]
        public double OffsetZ { get; set; }

        [JsonProperty("Water")]
        public Water3 Water { get; set; }
    }

}
