// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Damage
    {

        [JsonProperty("Type")]
        public string Type { get; set; }

        [JsonProperty("Amount")]
        public int Amount { get; set; }

        [JsonProperty("Radius")]
        public int Radius { get; set; }

        [JsonProperty("DamageFriendly")]
        public bool DamageFriendly { get; set; }
    }

}
