// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Defense
    {

        [JsonProperty("MaxHealth")]
        public int MaxHealth { get; set; }

        [JsonProperty("Health")]
        public int Health { get; set; }

        [JsonProperty("ArmorType")]
        public string ArmorType { get; set; }

        [JsonProperty("Shield")]
        public Shield Shield { get; set; }

        [JsonProperty("SubThreatLevel")]
        public double? SubThreatLevel { get; set; }

        [JsonProperty("RegenRate")]
        public double? RegenRate { get; set; }

        [JsonProperty("SurfaceThreatLevel")]
        public double? SurfaceThreatLevel { get; set; }

        [JsonProperty("EconomyThreatLevel")]
        public double? EconomyThreatLevel { get; set; }

        [JsonProperty("AirThreatLevel")]
        public double? AirThreatLevel { get; set; }

        [JsonProperty("ThreatLevel")]
        public int? ThreatLevel { get; set; }

        [JsonProperty("AntiMissile")]
        public AntiMissile AntiMissile { get; set; }

        [JsonProperty("InstantDeath")]
        public bool? InstantDeath { get; set; }
    }

}
