// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Effect16
    {

        [JsonProperty("Bones")]
        public IList<object> Bones { get; set; }

        [JsonProperty("Type")]
        public string Type { get; set; }

        [JsonProperty("Scale")]
        public int? Scale { get; set; }
    }

}
