// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class EngineeringPod
    {

        [JsonProperty("PodUnitID")]
        public string PodUnitID { get; set; }

        [JsonProperty("CreateWithUnit")]
        public bool CreateWithUnit { get; set; }

        [JsonProperty("PodName")]
        public string PodName { get; set; }

        [JsonProperty("PodAttachpoint")]
        public string PodAttachpoint { get; set; }
    }

}
