// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Enhancements
    {

        [JsonProperty("DamageStabilizationRemove")]
        public DamageStabilizationRemove DamageStabilizationRemove { get; set; }

        [JsonProperty("Teleporter")]
        public Teleporter Teleporter { get; set; }

        [JsonProperty("Slots")]
        public Slots Slots { get; set; }

        [JsonProperty("Shield")]
        public Shield2 Shield { get; set; }

        [JsonProperty("TeleporterRemove")]
        public TeleporterRemove TeleporterRemove { get; set; }

        [JsonProperty("MissileRemove")]
        public MissileRemove MissileRemove { get; set; }

        [JsonProperty("ShieldRemove")]
        public ShieldRemove ShieldRemove { get; set; }

        [JsonProperty("Missile")]
        public Missile Missile { get; set; }

        [JsonProperty("OverchargeRemove")]
        public OverchargeRemove OverchargeRemove { get; set; }

        [JsonProperty("EnhancedSensorsRemove")]
        public EnhancedSensorsRemove EnhancedSensorsRemove { get; set; }

        [JsonProperty("Overcharge")]
        public Overcharge Overcharge { get; set; }

        [JsonProperty("EnhancedSensors")]
        public EnhancedSensors EnhancedSensors { get; set; }

        [JsonProperty("DamageStabilization")]
        public DamageStabilization DamageStabilization { get; set; }

        [JsonProperty("EngineeringThroughput")]
        public EngineeringThroughput EngineeringThroughput { get; set; }

        [JsonProperty("EngineeringThroughputRemove")]
        public EngineeringThroughputRemove EngineeringThroughputRemove { get; set; }

        [JsonProperty("ResourceAllocationRemove")]
        public ResourceAllocationRemove ResourceAllocationRemove { get; set; }

        [JsonProperty("StabilitySuppressant")]
        public StabilitySuppressant StabilitySuppressant { get; set; }

        [JsonProperty("Sacrifice")]
        public Sacrifice Sacrifice { get; set; }

        [JsonProperty("StabilitySuppressantRemove")]
        public StabilitySuppressantRemove StabilitySuppressantRemove { get; set; }

        [JsonProperty("ShieldHeavyRemove")]
        public ShieldHeavyRemove ShieldHeavyRemove { get; set; }

        [JsonProperty("ShieldHeavy")]
        public ShieldHeavy ShieldHeavy { get; set; }

        [JsonProperty("SacrificeRemove")]
        public SacrificeRemove SacrificeRemove { get; set; }

        [JsonProperty("EngineeringFocusingModule")]
        public EngineeringFocusingModule EngineeringFocusingModule { get; set; }

        [JsonProperty("EngineeringFocusingModuleRemove")]
        public EngineeringFocusingModuleRemove EngineeringFocusingModuleRemove { get; set; }

        [JsonProperty("ResourceAllocation")]
        public ResourceAllocation ResourceAllocation { get; set; }

        [JsonProperty("SystemIntegrityCompensator")]
        public SystemIntegrityCompensator SystemIntegrityCompensator { get; set; }

        [JsonProperty("SystemIntegrityCompensatorRemove")]
        public SystemIntegrityCompensatorRemove SystemIntegrityCompensatorRemove { get; set; }

        [JsonProperty("SensorRangeEnhancerRemove")]
        public SensorRangeEnhancerRemove SensorRangeEnhancerRemove { get; set; }

        [JsonProperty("RadarJammer")]
        public RadarJammer RadarJammer { get; set; }

        [JsonProperty("PodRemove")]
        public PodRemove PodRemove { get; set; }

        [JsonProperty("ShieldGeneratorFieldRemove")]
        public ShieldGeneratorFieldRemove ShieldGeneratorFieldRemove { get; set; }

        [JsonProperty("AdvancedCoolingUpgradeRemove")]
        public AdvancedCoolingUpgradeRemove AdvancedCoolingUpgradeRemove { get; set; }

        [JsonProperty("ShieldGeneratorField")]
        public ShieldGeneratorField ShieldGeneratorField { get; set; }

        [JsonProperty("HighExplosiveOrdnanceRemove")]
        public HighExplosiveOrdnanceRemove HighExplosiveOrdnanceRemove { get; set; }

        [JsonProperty("HighExplosiveOrdnance")]
        public HighExplosiveOrdnance HighExplosiveOrdnance { get; set; }

        [JsonProperty("AdvancedCoolingUpgrade")]
        public AdvancedCoolingUpgrade AdvancedCoolingUpgrade { get; set; }

        [JsonProperty("Pod")]
        public Pod Pod { get; set; }

        [JsonProperty("SensorRangeEnhancer")]
        public SensorRangeEnhancer SensorRangeEnhancer { get; set; }

        [JsonProperty("RadarJammerRemove")]
        public RadarJammerRemove RadarJammerRemove { get; set; }

        [JsonProperty("FocusConvertor")]
        public FocusConvertor FocusConvertor { get; set; }

        [JsonProperty("CloakingGenerator")]
        public CloakingGenerator CloakingGenerator { get; set; }

        [JsonProperty("FocusConvertorRemove")]
        public FocusConvertorRemove FocusConvertorRemove { get; set; }

        [JsonProperty("NaniteMissileSystem")]
        public NaniteMissileSystem NaniteMissileSystem { get; set; }

        [JsonProperty("NaniteMissileSystemRemove")]
        public NaniteMissileSystemRemove NaniteMissileSystemRemove { get; set; }

        [JsonProperty("EMPChargeRemove")]
        public EMPChargeRemove EMPChargeRemove { get; set; }

        [JsonProperty("SwitchbackRemove")]
        public SwitchbackRemove SwitchbackRemove { get; set; }

        [JsonProperty("Switchback")]
        public Switchback Switchback { get; set; }

        [JsonProperty("EMPCharge")]
        public EMPCharge EMPCharge { get; set; }

        [JsonProperty("CloakingGeneratorRemove")]
        public CloakingGeneratorRemove CloakingGeneratorRemove { get; set; }

        [JsonProperty("StealthGenerator")]
        public StealthGenerator StealthGenerator { get; set; }

        [JsonProperty("StealthGeneratorRemove")]
        public StealthGeneratorRemove StealthGeneratorRemove { get; set; }

        [JsonProperty("SelfRepairSystem")]
        public SelfRepairSystem SelfRepairSystem { get; set; }

        [JsonProperty("SelfRepairSystemRemove")]
        public SelfRepairSystemRemove SelfRepairSystemRemove { get; set; }

        [JsonProperty("TacticalNukeMissileRemove")]
        public TacticalNukeMissileRemove TacticalNukeMissileRemove { get; set; }

        [JsonProperty("AdvancedEngineeringRemove")]
        public AdvancedEngineeringRemove AdvancedEngineeringRemove { get; set; }

        [JsonProperty("HeavyAntiMatterCannonRemove")]
        public HeavyAntiMatterCannonRemove HeavyAntiMatterCannonRemove { get; set; }

        [JsonProperty("DamageStablizationRemove")]
        public DamageStablizationRemove DamageStablizationRemove { get; set; }

        [JsonProperty("HeavyAntiMatterCannon")]
        public HeavyAntiMatterCannon HeavyAntiMatterCannon { get; set; }

        [JsonProperty("DamageStablization")]
        public DamageStablization DamageStablization { get; set; }

        [JsonProperty("LeftPod")]
        public LeftPod LeftPod { get; set; }

        [JsonProperty("LeftPodRemove")]
        public LeftPodRemove LeftPodRemove { get; set; }

        [JsonProperty("AdvancedEngineering")]
        public AdvancedEngineering AdvancedEngineering { get; set; }

        [JsonProperty("RightPod")]
        public RightPod RightPod { get; set; }

        [JsonProperty("T3EngineeringRemove")]
        public T3EngineeringRemove T3EngineeringRemove { get; set; }

        [JsonProperty("T3Engineering")]
        public T3Engineering T3Engineering { get; set; }

        [JsonProperty("TacticalMissile")]
        public TacticalMissile TacticalMissile { get; set; }

        [JsonProperty("RightPodRemove")]
        public RightPodRemove RightPodRemove { get; set; }

        [JsonProperty("TacticalMissileRemove")]
        public TacticalMissileRemove TacticalMissileRemove { get; set; }

        [JsonProperty("TacticalNukeMissile")]
        public TacticalNukeMissile TacticalNukeMissile { get; set; }

        [JsonProperty("ChronoDampener")]
        public ChronoDampener ChronoDampener { get; set; }

        [JsonProperty("CrysalisBeamRemove")]
        public CrysalisBeamRemove CrysalisBeamRemove { get; set; }

        [JsonProperty("HeatSinkRemove")]
        public HeatSinkRemove HeatSinkRemove { get; set; }

        [JsonProperty("HeatSink")]
        public HeatSink HeatSink { get; set; }

        [JsonProperty("ChronoDampenerRemove")]
        public ChronoDampenerRemove ChronoDampenerRemove { get; set; }

        [JsonProperty("ResourceAllocationAdvanced")]
        public ResourceAllocationAdvanced ResourceAllocationAdvanced { get; set; }

        [JsonProperty("ResourceAllocationAdvancedRemove")]
        public ResourceAllocationAdvancedRemove ResourceAllocationAdvancedRemove { get; set; }

        [JsonProperty("CrysalisBeam")]
        public CrysalisBeam CrysalisBeam { get; set; }

        [JsonProperty("CoolingUpgradeRemove")]
        public CoolingUpgradeRemove CoolingUpgradeRemove { get; set; }

        [JsonProperty("NaniteTorpedoTube")]
        public NaniteTorpedoTube NaniteTorpedoTube { get; set; }

        [JsonProperty("MicrowaveLaserGeneratorRemove")]
        public MicrowaveLaserGeneratorRemove MicrowaveLaserGeneratorRemove { get; set; }

        [JsonProperty("CoolingUpgrade")]
        public CoolingUpgrade CoolingUpgrade { get; set; }

        [JsonProperty("NaniteTorpedoTubeRemove")]
        public NaniteTorpedoTubeRemove NaniteTorpedoTubeRemove { get; set; }

        [JsonProperty("MicrowaveLaserGenerator")]
        public MicrowaveLaserGenerator MicrowaveLaserGenerator { get; set; }

        [JsonProperty("RateOfFireRemove")]
        public RateOfFireRemove RateOfFireRemove { get; set; }

        [JsonProperty("DamageStabilizationAdvanced")]
        public DamageStabilizationAdvanced DamageStabilizationAdvanced { get; set; }

        [JsonProperty("DamageStabilizationAdvancedRemove")]
        public DamageStabilizationAdvancedRemove DamageStabilizationAdvancedRemove { get; set; }

        [JsonProperty("AdvancedRegenAura")]
        public AdvancedRegenAura AdvancedRegenAura { get; set; }

        [JsonProperty("AdvancedRegenAuraRemove")]
        public AdvancedRegenAuraRemove AdvancedRegenAuraRemove { get; set; }

        [JsonProperty("RateOfFire")]
        public RateOfFire RateOfFire { get; set; }

        [JsonProperty("BlastAttack")]
        public BlastAttack BlastAttack { get; set; }

        [JsonProperty("RegenAura")]
        public RegenAura RegenAura { get; set; }

        [JsonProperty("BlastAttackRemove")]
        public BlastAttackRemove BlastAttackRemove { get; set; }

        [JsonProperty("RegenAuraRemove")]
        public RegenAuraRemove RegenAuraRemove { get; set; }
    }

}
