// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class EnhancementPresetAssigned
    {

        [JsonProperty("Enhancements")]
        public IList<string> Enhancements { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("BaseBlueprintId")]
        public string BaseBlueprintId { get; set; }
    }

}
