// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class EnhancementPresets
    {

        [JsonProperty("Rambo")]
        public Rambo Rambo { get; set; }

        [JsonProperty("Combat")]
        public Combat Combat { get; set; }

        [JsonProperty("AntiAir")]
        public AntiAir AntiAir { get; set; }

        [JsonProperty("Stealth")]
        public Stealth Stealth { get; set; }

        [JsonProperty("Engineer")]
        public Engineer Engineer { get; set; }

        [JsonProperty("Cloak")]
        public Cloak Cloak { get; set; }

        [JsonProperty("Missile")]
        public Missile2 Missile { get; set; }

        [JsonProperty("AdvancedCombat")]
        public AdvancedCombat AdvancedCombat { get; set; }

        [JsonProperty("NanoCombat")]
        public NanoCombat NanoCombat { get; set; }

        [JsonProperty("IntelJammer")]
        public IntelJammer IntelJammer { get; set; }

        [JsonProperty("BubbleShield")]
        public BubbleShield BubbleShield { get; set; }

        [JsonProperty("SimpleCombat")]
        public SimpleCombat SimpleCombat { get; set; }

        [JsonProperty("ShieldCombat")]
        public ShieldCombat ShieldCombat { get; set; }
    }

}
