// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class FireTargetLayerCapsTable
    {

        [JsonProperty("Water")]
        public string Water { get; set; }

        [JsonProperty("Land")]
        public string Land { get; set; }

        [JsonProperty("Seabed")]
        public string Seabed { get; set; }

        [JsonProperty("Sub")]
        public string Sub { get; set; }

        [JsonProperty("Air")]
        public string Air { get; set; }
    }

}
