// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Flare
    {

        [JsonProperty("Radius")]
        public int Radius { get; set; }

        [JsonProperty("Category")]
        public string Category { get; set; }
    }

}
