// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Footprint2
    {

        [JsonProperty("SizeX")]
        public double SizeX { get; set; }

        [JsonProperty("SizeZ")]
        public int SizeZ { get; set; }

        [JsonProperty("SizeY")]
        public double? SizeY { get; set; }
    }

}
