// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class General
    {

        [JsonProperty("TechLevel")]
        public object TechLevel { get; set; }

        [JsonProperty("SeedUnit")]
        public string SeedUnit { get; set; }

        [JsonProperty("UnitWeight")]
        public int UnitWeight { get; set; }

        [JsonProperty("UpgradesFromBase")]
        public string UpgradesFromBase { get; set; }

        [JsonProperty("Category")]
        public string Category { get; set; }

        [JsonProperty("UnitName")]
        public string UnitName { get; set; }

        [JsonProperty("Icon")]
        public string Icon { get; set; }

        [JsonProperty("CommandCaps")]
        public string CommandCaps { get; set; }

        [JsonProperty("Classification")]
        public string Classification { get; set; }

        [JsonProperty("QuickSelectPriority")]
        public int QuickSelectPriority { get; set; }

        [JsonProperty("CapCost")]
        public double CapCost { get; set; }

        [JsonProperty("UpgradesFrom")]
        public string UpgradesFrom { get; set; }

        [JsonProperty("FactionName")]
        public string FactionName { get; set; }

        [JsonProperty("ToggleCaps")]
        public string ToggleCaps { get; set; }

        [JsonProperty("SelectionPriority")]
        public int SelectionPriority { get; set; }

        [JsonProperty("UpgradesTo")]
        public string UpgradesTo { get; set; }

        [JsonProperty("EntityCategory")]
        public IList<string> EntityCategory { get; set; }

        [JsonProperty("Faction")]
        public string Faction { get; set; }

        [JsonProperty("Weapon")]
        public string Weapon { get; set; }

        [JsonProperty("BuildBones")]
        public BuildBones BuildBones { get; set; }

        [JsonProperty("OrderOverrides")]
        public OrderOverrides OrderOverrides { get; set; }

        [JsonProperty("ConstructionBar")]
        public bool? ConstructionBar { get; set; }

        [JsonProperty("TarmacGlowDecal")]
        public object TarmacGlowDecal { get; set; }

        [JsonProperty("TarmacDecal")]
        public string TarmacDecal { get; set; }

        [JsonProperty("InstantDeathOnSelfDestruct")]
        public bool? InstantDeathOnSelfDestruct { get; set; }

        [JsonProperty("BuildBonesAlt1")]
        public BuildBonesAlt1 BuildBonesAlt1 { get; set; }
    }

}
