// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class IdleEffects
    {

        [JsonProperty("Seabed")]
        public Seabed2 Seabed { get; set; }

        [JsonProperty("Water")]
        public Water2 Water { get; set; }

        [JsonProperty("Land")]
        public Land2 Land { get; set; }

        [JsonProperty("Air")]
        public Air2 Air { get; set; }

        [JsonProperty("Sub")]
        public Sub2 Sub { get; set; }
    }

}
