// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Intel
    {

        [JsonProperty("JammerBlips")]
        public int JammerBlips { get; set; }

        [JsonProperty("RadarStealth")]
        public bool RadarStealth { get; set; }

        [JsonProperty("SonarRadius")]
        public int SonarRadius { get; set; }

        [JsonProperty("Cloak")]
        public bool Cloak { get; set; }

        [JsonProperty("SpoofRadius")]
        public SpoofRadius SpoofRadius { get; set; }

        [JsonProperty("OmniRadius")]
        public int OmniRadius { get; set; }

        [JsonProperty("RadarRadius")]
        public int RadarRadius { get; set; }

        [JsonProperty("JamRadius")]
        public JamRadius JamRadius { get; set; }

        [JsonProperty("SonarStealthFieldRadius")]
        public int SonarStealthFieldRadius { get; set; }

        [JsonProperty("RadarStealthFieldRadius")]
        public int RadarStealthFieldRadius { get; set; }

        [JsonProperty("VisionRadius")]
        public int VisionRadius { get; set; }

        [JsonProperty("CloakFieldRadius")]
        public int CloakFieldRadius { get; set; }

        [JsonProperty("ShowIntelOnSelect")]
        public bool ShowIntelOnSelect { get; set; }

        [JsonProperty("WaterVisionRadius")]
        public int WaterVisionRadius { get; set; }

        [JsonProperty("SonarStealth")]
        public bool SonarStealth { get; set; }

        [JsonProperty("FreeIntel")]
        public bool? FreeIntel { get; set; }

        [JsonProperty("ReactivateTime")]
        public int? ReactivateTime { get; set; }

        [JsonProperty("RemoteViewingRadius")]
        public int? RemoteViewingRadius { get; set; }

        [JsonProperty("VisionRadiusOnDeath")]
        public int? VisionRadiusOnDeath { get; set; }

        [JsonProperty("IntelDurationOnDeath")]
        public int? IntelDurationOnDeath { get; set; }

        [JsonProperty("MaxVisionRadius")]
        public int? MaxVisionRadius { get; set; }

        [JsonProperty("MinVisionRadius")]
        public int? MinVisionRadius { get; set; }

        [JsonProperty("WaterVisionradius")]
        public int? WaterVisionradius { get; set; }

        [JsonProperty("RadarStealthField")]
        public bool? RadarStealthField { get; set; }

        [JsonProperty("StealthWaitTime")]
        public int? StealthWaitTime { get; set; }
    }

}
