// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Interface
    {

        [JsonProperty("HelpText")]
        public object HelpText { get; set; }

        [JsonProperty("Selectable")]
        public bool? Selectable { get; set; }
    }

}
