// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Land
    {

        [JsonProperty("Footfall")]
        public Footfall Footfall { get; set; }

        [JsonProperty("Effects")]
        public IList<Effect6> Effects { get; set; }

        [JsonProperty("Treads")]
        public Treads Treads { get; set; }

        [JsonProperty("CameraShake")]
        public CameraShake2 CameraShake { get; set; }
    }

}
