// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class LayerChangeEffects
    {

        [JsonProperty("AirLand")]
        public AirLand AirLand { get; set; }

        [JsonProperty("LandAir")]
        public LandAir LandAir { get; set; }

        [JsonProperty("SeabedLand")]
        public SeabedLand SeabedLand { get; set; }

        [JsonProperty("WaterLand")]
        public WaterLand WaterLand { get; set; }
    }

}
