// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class LOD
    {

        [JsonProperty("Silhouette")]
        public bool Silhouette { get; set; }

        [JsonProperty("ShaderName")]
        public string ShaderName { get; set; }

        [JsonProperty("AlbedoName")]
        public string AlbedoName { get; set; }

        [JsonProperty("SecondaryName")]
        public string SecondaryName { get; set; }

        [JsonProperty("Scrolling")]
        public bool Scrolling { get; set; }

        [JsonProperty("LookupName")]
        public string LookupName { get; set; }

        [JsonProperty("LODCutoff")]
        public int LODCutoff { get; set; }

        [JsonProperty("MeshName")]
        public string MeshName { get; set; }

        [JsonProperty("SpecularName")]
        public string SpecularName { get; set; }

        [JsonProperty("NormalsName")]
        public string NormalsName { get; set; }

        [JsonProperty("Occlude")]
        public bool Occlude { get; set; }

        [JsonProperty("SpecName")]
        public string SpecName { get; set; }

        [JsonProperty("Shader")]
        public string Shader { get; set; }

        [JsonProperty("TextureName")]
        public string TextureName { get; set; }
    }

}
