// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Mesh2
    {

        [JsonProperty("IconFadeInZoom")]
        public int IconFadeInZoom { get; set; }

        [JsonProperty("LODs")]
        public IList<LOD2> LODs { get; set; }

        [JsonProperty("MeshName")]
        public string MeshName { get; set; }
    }

}
