// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Mesh
    {

        [JsonProperty("Source")]
        public string Source { get; set; }

        [JsonProperty("BlueprintId")]
        public string BlueprintId { get; set; }

        [JsonProperty("UniformScale")]
        public int UniformScale { get; set; }

        [JsonProperty("LODs")]
        public IList<LOD> LODs { get; set; }

        [JsonProperty("BlueprintOrdinal")]
        public int BlueprintOrdinal { get; set; }

        [JsonProperty("IconFadeInZoom")]
        public int IconFadeInZoom { get; set; }

        [JsonProperty("SortOrder")]
        public int SortOrder { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("StraddleWater")]
        public bool StraddleWater { get; set; }
    }

}
