// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class MotionChangeEffects
    {

        [JsonProperty("WaterTopDown")]
        public WaterTopDown WaterTopDown { get; set; }

        [JsonProperty("SubBottomUp")]
        public SubBottomUp SubBottomUp { get; set; }
    }

}
