// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class MotionAdjustment
    {

        [JsonProperty("Sliderlanding")]
        public double Sliderlanding { get; set; }

        [JsonProperty("Sliderstatic")]
        public int Sliderstatic { get; set; }

        [JsonProperty("Yoffsetlanding")]
        public double Yoffsetlanding { get; set; }

        [JsonProperty("slideinmotion")]
        public double Slideinmotion { get; set; }

        [JsonProperty("Yoffsetinmotion")]
        public double Yoffsetinmotion { get; set; }
    }

}
