// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class OrderOverrides
    {

        [JsonProperty("RULEUTC_ShieldToggle")]
        public RULEUTCShieldToggle RULEUTCShieldToggle { get; set; }

        [JsonProperty("RULEUCC_Transport")]
        public RULEUCCTransport RULEUCCTransport { get; set; }

        [JsonProperty("RULEUTC_IntelToggle")]
        public RULEUTCIntelToggle RULEUTCIntelToggle { get; set; }

        [JsonProperty("RULEUTC_StealthToggle")]
        public RULEUTCStealthToggle RULEUTCStealthToggle { get; set; }

        [JsonProperty("DroneL")]
        public DroneL DroneL { get; set; }

        [JsonProperty("RULEUTC_ProductionToggle")]
        public RULEUTCProductionToggle RULEUTCProductionToggle { get; set; }

        [JsonProperty("RULEUCC_SiloBuildNuke")]
        public RULEUCCSiloBuildNuke RULEUCCSiloBuildNuke { get; set; }

        [JsonProperty("RULEUCC_Nuke")]
        public RULEUCCNuke RULEUCCNuke { get; set; }

        [JsonProperty("RULEUTC_WeaponToggle")]
        public RULEUTCWeaponToggle RULEUTCWeaponToggle { get; set; }

        [JsonProperty("DroneR")]
        public DroneR DroneR { get; set; }

        [JsonProperty("RULEUTC_JammingToggle")]
        public RULEUTCJammingToggle RULEUTCJammingToggle { get; set; }
    }

}
