// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Physics
    {

        [JsonProperty("BlockPath")]
        public bool BlockPath { get; set; }

        [JsonProperty("AltMotionType")]
        public string AltMotionType { get; set; }

        [JsonProperty("LayerChangeOffsetHeight")]
        public double? LayerChangeOffsetHeight { get; set; }

        [JsonProperty("MaxAcceleration")]
        public double? MaxAcceleration { get; set; }

        [JsonProperty("FuelRechargeRate")]
        public int? FuelRechargeRate { get; set; }

        [JsonProperty("MotionType")]
        public string MotionType { get; set; }

        [JsonProperty("RotateOnSpot")]
        public bool? RotateOnSpot { get; set; }

        [JsonProperty("BuildRestriction")]
        public string BuildRestriction { get; set; }

        [JsonProperty("MaxGroundVariation")]
        public int? MaxGroundVariation { get; set; }

        [JsonProperty("TurnRate")]
        public int? TurnRate { get; set; }

        [JsonProperty("MaxSteerForce")]
        public double? MaxSteerForce { get; set; }

        [JsonProperty("SkirtOffsetZ")]
        public double? SkirtOffsetZ { get; set; }

        [JsonProperty("BuildOnLayerCaps")]
        public string BuildOnLayerCaps { get; set; }

        [JsonProperty("MeshExtentsY")]
        public double? MeshExtentsY { get; set; }

        [JsonProperty("MinSpeedPercent")]
        public double? MinSpeedPercent { get; set; }

        [JsonProperty("RollDamping")]
        public double? RollDamping { get; set; }

        [JsonProperty("LayerTransitionDuration")]
        public int? LayerTransitionDuration { get; set; }

        [JsonProperty("MeshExtentsX")]
        public double? MeshExtentsX { get; set; }

        [JsonProperty("TurnFacingRate")]
        public int? TurnFacingRate { get; set; }

        [JsonProperty("WobbleFactor")]
        public double? WobbleFactor { get; set; }

        [JsonProperty("TurnRadius")]
        public double? TurnRadius { get; set; }

        [JsonProperty("WobbleSpeed")]
        public double? WobbleSpeed { get; set; }

        [JsonProperty("CatchUpAcc")]
        public double? CatchUpAcc { get; set; }

        [JsonProperty("SkirtSizeZ")]
        public int? SkirtSizeZ { get; set; }

        [JsonProperty("GroundCollisionOffset")]
        public double? GroundCollisionOffset { get; set; }

        [JsonProperty("FlattenSkirt")]
        public bool? FlattenSkirt { get; set; }

        [JsonProperty("MeshExtentsZ")]
        public double? MeshExtentsZ { get; set; }

        [JsonProperty("SinkLower")]
        public bool? SinkLower { get; set; }

        [JsonProperty("MaxSpeedReverse")]
        public double? MaxSpeedReverse { get; set; }

        [JsonProperty("StandUpright")]
        public bool? StandUpright { get; set; }

        [JsonProperty("Elevation")]
        public double? Elevation { get; set; }

        [JsonProperty("DiveSurfaceSpeed")]
        public int? DiveSurfaceSpeed { get; set; }

        [JsonProperty("BankingSlope")]
        public double? BankingSlope { get; set; }

        [JsonProperty("RollStability")]
        public double? RollStability { get; set; }

        [JsonProperty("AttackElevation")]
        public double? AttackElevation { get; set; }

        [JsonProperty("RotateBodyWhileMoving")]
        public bool? RotateBodyWhileMoving { get; set; }

        [JsonProperty("RotateOnSpotThreshold")]
        public double? RotateOnSpotThreshold { get; set; }

        [JsonProperty("MaxSpeed")]
        public double? MaxSpeed { get; set; }

        [JsonProperty("BackUpDistance")]
        public double? BackUpDistance { get; set; }

        [JsonProperty("FuelUseTime")]
        public int? FuelUseTime { get; set; }

        [JsonProperty("SkirtSizeX")]
        public int? SkirtSizeX { get; set; }

        [JsonProperty("SkirtOffsetX")]
        public double? SkirtOffsetX { get; set; }

        [JsonProperty("MaxBrake")]
        public double? MaxBrake { get; set; }

        [JsonProperty("TurnRateRange")]
        public int? TurnRateRange { get; set; }

        [JsonProperty("MinBounceCount")]
        public int? MinBounceCount { get; set; }

        [JsonProperty("InitialSpeedRange")]
        public double? InitialSpeedRange { get; set; }

        [JsonProperty("MaxBounceCount")]
        public int? MaxBounceCount { get; set; }

        [JsonProperty("Lifetime")]
        public double? Lifetime { get; set; }

        [JsonProperty("LifetimeRange")]
        public int? LifetimeRange { get; set; }

        [JsonProperty("CollideEntity")]
        public bool? CollideEntity { get; set; }

        [JsonProperty("StayUnderwater")]
        public bool? StayUnderwater { get; set; }

        [JsonProperty("DirectionX")]
        public int? DirectionX { get; set; }

        [JsonProperty("PositionXRange")]
        public int? PositionXRange { get; set; }

        [JsonProperty("DirectionYRange")]
        public double? DirectionYRange { get; set; }

        [JsonProperty("DestroyOnWater")]
        public bool? DestroyOnWater { get; set; }

        [JsonProperty("VelocityAlign")]
        public bool? VelocityAlign { get; set; }

        [JsonProperty("CollideSurface")]
        public bool? CollideSurface { get; set; }

        [JsonProperty("PositionZRange")]
        public int? PositionZRange { get; set; }

        [JsonProperty("TrackTarget")]
        public bool? TrackTarget { get; set; }

        [JsonProperty("DirectionXRange")]
        public double? DirectionXRange { get; set; }

        [JsonProperty("UseGravity")]
        public bool? UseGravity { get; set; }

        [JsonProperty("PositionY")]
        public double? PositionY { get; set; }

        [JsonProperty("MaxZigZag")]
        public double? MaxZigZag { get; set; }

        [JsonProperty("MaxSpeedRange")]
        public int? MaxSpeedRange { get; set; }

        [JsonProperty("DirectionZ")]
        public int? DirectionZ { get; set; }

        [JsonProperty("RotationalVelocity")]
        public int? RotationalVelocity { get; set; }

        [JsonProperty("StraightDownOrdinance")]
        public bool? StraightDownOrdinance { get; set; }

        [JsonProperty("InitialSpeed")]
        public double? InitialSpeed { get; set; }

        [JsonProperty("Acceleration")]
        public double? Acceleration { get; set; }

        [JsonProperty("LeadTarget")]
        public bool? LeadTarget { get; set; }

        [JsonProperty("PositionYRange")]
        public int? PositionYRange { get; set; }

        [JsonProperty("DirectionZRange")]
        public double? DirectionZRange { get; set; }

        [JsonProperty("AccelerationRange")]
        public int? AccelerationRange { get; set; }

        [JsonProperty("DirectionY")]
        public double? DirectionY { get; set; }

        [JsonProperty("BounceVelDamp")]
        public double? BounceVelDamp { get; set; }

        [JsonProperty("DetonateBelowHeight")]
        public int? DetonateBelowHeight { get; set; }

        [JsonProperty("StayUpright")]
        public bool? StayUpright { get; set; }

        [JsonProperty("PositionX")]
        public int? PositionX { get; set; }

        [JsonProperty("RealisticOrdinance")]
        public bool? RealisticOrdinance { get; set; }

        [JsonProperty("DetonateAboveHeight")]
        public int? DetonateAboveHeight { get; set; }

        [JsonProperty("PositionZ")]
        public int? PositionZ { get; set; }

        [JsonProperty("RotationalVelocityRange")]
        public double? RotationalVelocityRange { get; set; }

        [JsonProperty("ZigZagFrequency")]
        public double? ZigZagFrequency { get; set; }

        [JsonProperty("DragCoefficient")]
        public double? DragCoefficient { get; set; }

        [JsonProperty("RotationalAcceleration")]
        public int? RotationalAcceleration { get; set; }

        [JsonProperty("Footprint")]
        public Footprint2 Footprint { get; set; }

        [JsonProperty("InitialSpeedReduceDistance")]
        public int? InitialSpeedReduceDistance { get; set; }

        [JsonProperty("CollideFriendlyShield")]
        public bool? CollideFriendlyShield { get; set; }

        [JsonProperty("TrackTargetGround")]
        public bool? TrackTargetGround { get; set; }

        [JsonProperty("LifeTime")]
        public int? LifeTime { get; set; }

        [JsonProperty("ProjectileLifetime")]
        public double? ProjectileLifetime { get; set; }

        [JsonProperty("RollOffPoints")]
        public IList<RollOffPoint> RollOffPoints { get; set; }

        [JsonProperty("RaisedPlatforms")]
        public IList<double> RaisedPlatforms { get; set; }

        [JsonProperty("FootprintSizeX")]
        public int? FootprintSizeX { get; set; }

        [JsonProperty("FootprintSizeZ")]
        public int? FootprintSizeZ { get; set; }

        [JsonProperty("HitAssignedTarget")]
        public bool? HitAssignedTarget { get; set; }

        [JsonProperty("OccupyRects")]
        public IList<double> OccupyRects { get; set; }

        [JsonProperty("MeshExtentsOffsetY")]
        public double? MeshExtentsOffsetY { get; set; }

        [JsonProperty("OnLostTargetLifetime")]
        public double? OnLostTargetLifetime { get; set; }

        [JsonProperty("CollisionOffsetX")]
        public int? CollisionOffsetX { get; set; }

        [JsonProperty("BackupDistance")]
        public int? BackupDistance { get; set; }

        [JsonProperty("FlareRadius")]
        public int? FlareRadius { get; set; }

        [JsonProperty("WaterSpeedMultiplier")]
        public double? WaterSpeedMultiplier { get; set; }

        [JsonProperty("LandSpeedMultiplier")]
        public double? LandSpeedMultiplier { get; set; }

        [JsonProperty("SinkSpeed")]
        public double? SinkSpeed { get; set; }
    }

}
