// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class PingPongScroller
    {

        [JsonProperty("Pong1")]
        public double Pong1 { get; set; }

        [JsonProperty("Pong2Speed")]
        public double Pong2Speed { get; set; }

        [JsonProperty("Pong2")]
        public double Pong2 { get; set; }

        [JsonProperty("Ping2")]
        public double Ping2 { get; set; }

        [JsonProperty("Pong1Speed")]
        public double Pong1Speed { get; set; }

        [JsonProperty("Ping2Speed")]
        public double Ping2Speed { get; set; }

        [JsonProperty("Ping1")]
        public double Ping1 { get; set; }

        [JsonProperty("Ping1Speed")]
        public double Ping1Speed { get; set; }
    }

}
