// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class RackBone
    {

        [JsonProperty("MuzzleBones")]
        public IList<object> MuzzleBones { get; set; }

        [JsonProperty("RackBone")]
        public object RackBone1 { get; set; }

        [JsonProperty("HideMuzzle")]
        public bool? HideMuzzle { get; set; }

        [JsonProperty("TelescopeBone")]
        public string TelescopeBone { get; set; }

        [JsonProperty("TelescopeRecoilDistance")]
        public int? TelescopeRecoilDistance { get; set; }
    }

}
