// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class RegenAura
    {

        [JsonProperty("Radius")]
        public int Radius { get; set; }

        [JsonProperty("RegenFloor")]
        public int RegenFloor { get; set; }

        [JsonProperty("Slot")]
        public string Slot { get; set; }

        [JsonProperty("ShowBones")]
        public IList<string> ShowBones { get; set; }

        [JsonProperty("RegenPerSecond")]
        public double RegenPerSecond { get; set; }

        [JsonProperty("BuildCostEnergy")]
        public int BuildCostEnergy { get; set; }

        [JsonProperty("BuildTime")]
        public int BuildTime { get; set; }

        [JsonProperty("ACUAddHealth")]
        public int ACUAddHealth { get; set; }

        [JsonProperty("RegenCeiling")]
        public int RegenCeiling { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("BuildCostMass")]
        public int BuildCostMass { get; set; }

        [JsonProperty("UnitCategory")]
        public string UnitCategory { get; set; }

        [JsonProperty("UpgradeUnitAmbientBones")]
        public IList<string> UpgradeUnitAmbientBones { get; set; }

        [JsonProperty("Icon")]
        public string Icon { get; set; }

        [JsonProperty("UpgradeEffectBones")]
        public IList<string> UpgradeEffectBones { get; set; }
    }

}
