// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Regen
    {

        [JsonProperty("Level2")]
        public int Level2 { get; set; }

        [JsonProperty("Level3")]
        public int Level3 { get; set; }

        [JsonProperty("Level1")]
        public int Level1 { get; set; }

        [JsonProperty("Level4")]
        public int Level4 { get; set; }

        [JsonProperty("Level5")]
        public int Level5 { get; set; }
    }

}
