// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class RULEUTCStealthToggle
    {

        [JsonProperty("helpText")]
        public string HelpText { get; set; }

        [JsonProperty("bitmapId")]
        public string BitmapId { get; set; }
    }

}
