// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Shield2
    {

        [JsonProperty("UpgradeEffectBones")]
        public IList<string> UpgradeEffectBones { get; set; }

        [JsonProperty("BuildCostEnergy")]
        public int BuildCostEnergy { get; set; }

        [JsonProperty("BuildTime")]
        public int BuildTime { get; set; }

        [JsonProperty("ShieldRegenRate")]
        public int ShieldRegenRate { get; set; }

        [JsonProperty("OwnerShieldMesh")]
        public string OwnerShieldMesh { get; set; }

        [JsonProperty("ImpactEffects")]
        public string ImpactEffects { get; set; }

        [JsonProperty("Icon")]
        public string Icon { get; set; }

        [JsonProperty("Slot")]
        public string Slot { get; set; }

        [JsonProperty("ShowBones")]
        public IList<string> ShowBones { get; set; }

        [JsonProperty("ShieldEnergyDrainRechargeTime")]
        public int ShieldEnergyDrainRechargeTime { get; set; }

        [JsonProperty("ShieldRegenStartTime")]
        public int ShieldRegenStartTime { get; set; }

        [JsonProperty("ShieldMaxHealth")]
        public int ShieldMaxHealth { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("RegenAssistMult")]
        public int RegenAssistMult { get; set; }

        [JsonProperty("ShieldRechargeTime")]
        public int ShieldRechargeTime { get; set; }

        [JsonProperty("UpgradeUnitAmbientBones")]
        public IList<string> UpgradeUnitAmbientBones { get; set; }

        [JsonProperty("BuildCostMass")]
        public int BuildCostMass { get; set; }

        [JsonProperty("MaintenanceConsumptionPerSecondEnergy")]
        public int MaintenanceConsumptionPerSecondEnergy { get; set; }

        [JsonProperty("ShieldSize")]
        public int? ShieldSize { get; set; }

        [JsonProperty("ShieldVerticalOffset")]
        public int? ShieldVerticalOffset { get; set; }

        [JsonProperty("PersonalShield")]
        public bool? PersonalShield { get; set; }
    }

}
