// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Shield
    {

        [JsonProperty("ShieldSize")]
        public double ShieldSize { get; set; }

        [JsonProperty("RegenAssistMult")]
        public int RegenAssistMult { get; set; }

        [JsonProperty("ImpactMesh")]
        public string ImpactMesh { get; set; }

        [JsonProperty("ShieldEnergyDrainRechargeTime")]
        public int? ShieldEnergyDrainRechargeTime { get; set; }

        [JsonProperty("ShieldRegenStartTime")]
        public int? ShieldRegenStartTime { get; set; }

        [JsonProperty("MeshZ")]
        public string MeshZ { get; set; }

        [JsonProperty("ShieldRegenRate")]
        public int? ShieldRegenRate { get; set; }

        [JsonProperty("ImpactEffects")]
        public string ImpactEffects { get; set; }

        [JsonProperty("ShieldVerticalOffset")]
        public int? ShieldVerticalOffset { get; set; }

        [JsonProperty("ShieldRechargeTime")]
        public int? ShieldRechargeTime { get; set; }

        [JsonProperty("Mesh")]
        public string Mesh { get; set; }

        [JsonProperty("ShieldMaxHealth")]
        public int? ShieldMaxHealth { get; set; }

        [JsonProperty("PersonalShield")]
        public bool? PersonalShield { get; set; }

        [JsonProperty("OwnerShieldMesh")]
        public string OwnerShieldMesh { get; set; }

        [JsonProperty("StartOn")]
        public bool? StartOn { get; set; }

        [JsonProperty("ShieldSpillOverDamageMod")]
        public double? ShieldSpillOverDamageMod { get; set; }

        [JsonProperty("PersonalBubble")]
        public bool? PersonalBubble { get; set; }

        [JsonProperty("PassOverkillDamage")]
        public bool? PassOverkillDamage { get; set; }

        [JsonProperty("StartsOff")]
        public bool? StartsOff { get; set; }
    }

}
