// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Slots
    {

        [JsonProperty("RCH")]
        public RCH RCH { get; set; }

        [JsonProperty("Back")]
        public Back Back { get; set; }

        [JsonProperty("LCH")]
        public LCH LCH { get; set; }
    }

}
