// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class SplitDamage
    {

        [JsonProperty("DamageRadius")]
        public double DamageRadius { get; set; }

        [JsonProperty("DamageAmount")]
        public int DamageAmount { get; set; }
    }

}
