// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class SpoofRadius
    {

        [JsonProperty("Min")]
        public int Min { get; set; }

        [JsonProperty("Max")]
        public int Max { get; set; }
    }

}
