// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Tarmac
    {

        [JsonProperty("Normal")]
        public string Normal { get; set; }

        [JsonProperty("Orientations")]
        public IList<int> Orientations { get; set; }

        [JsonProperty("Albedo")]
        public string Albedo { get; set; }

        [JsonProperty("Width")]
        public double Width { get; set; }

        [JsonProperty("RemoveWhenDead")]
        public bool RemoveWhenDead { get; set; }

        [JsonProperty("Length")]
        public double Length { get; set; }

        [JsonProperty("DeathLifetime")]
        public int DeathLifetime { get; set; }

        [JsonProperty("FadeOut")]
        public int FadeOut { get; set; }
    }

}
