// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class TeleportEffects
    {

        [JsonProperty("PlayChargeFxAtUnit")]
        public bool PlayChargeFxAtUnit { get; set; }

        [JsonProperty("ChargeFxAtUnitBones")]
        public IList<ChargeFxAtUnitBone> ChargeFxAtUnitBones { get; set; }

        [JsonProperty("PlayTeleportOutFx")]
        public bool PlayTeleportOutFx { get; set; }

        [JsonProperty("PlayTeleportInFx")]
        public bool PlayTeleportInFx { get; set; }

        [JsonProperty("PlayChargeFxAtDestination")]
        public bool PlayChargeFxAtDestination { get; set; }

        [JsonProperty("TeleportAvatarUnit")]
        public string TeleportAvatarUnit { get; set; }

        [JsonProperty("FxSizeY")]
        public double? FxSizeY { get; set; }

        [JsonProperty("FxOffsetZ")]
        public double? FxOffsetZ { get; set; }

        [JsonProperty("FxSizeX")]
        public double? FxSizeX { get; set; }

        [JsonProperty("FxOffsetY")]
        public int? FxOffsetY { get; set; }

        [JsonProperty("FxOffsetX")]
        public int? FxOffsetX { get; set; }

        [JsonProperty("FxSizeZ")]
        public double? FxSizeZ { get; set; }
    }

}
