// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Transport
    {

        [JsonProperty("Class4AttachSize")]
        public int Class4AttachSize { get; set; }

        [JsonProperty("AirClass")]
        public bool AirClass { get; set; }

        [JsonProperty("Class3AttachSize")]
        public int Class3AttachSize { get; set; }

        [JsonProperty("ClassSAttachSize")]
        public int ClassSAttachSize { get; set; }

        [JsonProperty("DockingSlots")]
        public int DockingSlots { get; set; }

        [JsonProperty("StorageSlots")]
        public int StorageSlots { get; set; }

        [JsonProperty("ClassGenericUpTo")]
        public int ClassGenericUpTo { get; set; }

        [JsonProperty("Class2AttachSize")]
        public int Class2AttachSize { get; set; }

        [JsonProperty("RepairRate")]
        public double RepairRate { get; set; }

        [JsonProperty("TransportClass")]
        public int TransportClass { get; set; }

        [JsonProperty("CanFireFromTransport")]
        public bool? CanFireFromTransport { get; set; }

        [JsonProperty("Class1AttachSize")]
        public int? Class1AttachSize { get; set; }
    }

}
