// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class TransportDropAnimation
    {

        [JsonProperty("Animation")]
        public string Animation { get; set; }

        [JsonProperty("Weight")]
        public int Weight { get; set; }
    }

}
