// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Treads
    {

        [JsonProperty("ScrollTreads")]
        public bool ScrollTreads { get; set; }

        [JsonProperty("TreadMarks")]
        public IList<TreadMark> TreadMarks { get; set; }

        [JsonProperty("ScrollMultiplier")]
        public double? ScrollMultiplier { get; set; }
    }

}
