// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Tread
    {

        [JsonProperty("TreadMarksSizeX")]
        public double TreadMarksSizeX { get; set; }

        [JsonProperty("TreadMarksSizeZ")]
        public double TreadMarksSizeZ { get; set; }

        [JsonProperty("TreadOffset")]
        public IList<double> TreadOffset { get; set; }

        [JsonProperty("TreadMarks")]
        public string TreadMarks { get; set; }

        [JsonProperty("TreadLifeTime")]
        public int? TreadLifeTime { get; set; }
    }

}
