// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class Weapon
    {

        [JsonProperty("UseFiringSolutionInsteadOfAimBone")]
        public bool UseFiringSolutionInsteadOfAimBone { get; set; }

        [JsonProperty("FiringRandomness")]
        public double FiringRandomness { get; set; }

        [JsonProperty("Label")]
        public string Label { get; set; }

        [JsonProperty("TargetCheckInterval")]
        public double TargetCheckInterval { get; set; }

        [JsonProperty("EffectiveRadius")]
        public int EffectiveRadius { get; set; }

        [JsonProperty("HeadingArcCenter")]
        public int HeadingArcCenter { get; set; }

        [JsonProperty("DisplayName")]
        public string DisplayName { get; set; }

        [JsonProperty("BombDropThreshold")]
        public double BombDropThreshold { get; set; }

        [JsonProperty("DamageFriendly")]
        public bool DamageFriendly { get; set; }

        [JsonProperty("LeadTarget")]
        public bool LeadTarget { get; set; }

        [JsonProperty("WeaponCategory")]
        public string WeaponCategory { get; set; }

        [JsonProperty("AlwaysRecheckTarget")]
        public bool AlwaysRecheckTarget { get; set; }

        [JsonProperty("NukeWeapon")]
        public bool NukeWeapon { get; set; }

        [JsonProperty("TargetRestrictDisallow")]
        public string TargetRestrictDisallow { get; set; }

        [JsonProperty("AttackGroundTries")]
        public int AttackGroundTries { get; set; }

        [JsonProperty("DamageType")]
        public string DamageType { get; set; }

        [JsonProperty("FiringTolerance")]
        public double FiringTolerance { get; set; }

        [JsonProperty("MaxRadius")]
        public double MaxRadius { get; set; }

        [JsonProperty("AboveWaterFireOnly")]
        public bool AboveWaterFireOnly { get; set; }

        [JsonProperty("CannotAttackGround")]
        public bool CannotAttackGround { get; set; }

        [JsonProperty("AutoInitiateAttackCommand")]
        public bool AutoInitiateAttackCommand { get; set; }

        [JsonProperty("BelowWaterFireOnly")]
        public bool BelowWaterFireOnly { get; set; }

        [JsonProperty("MaxProjectileStorage")]
        public int MaxProjectileStorage { get; set; }

        [JsonProperty("MaximumBeamLength")]
        public int MaximumBeamLength { get; set; }

        [JsonProperty("DamageRadius")]
        public double DamageRadius { get; set; }

        [JsonProperty("RangeCategory")]
        public string RangeCategory { get; set; }

        [JsonProperty("ManualFire")]
        public bool ManualFire { get; set; }

        [JsonProperty("IgnoreIfDisabled")]
        public bool IgnoreIfDisabled { get; set; }

        [JsonProperty("UIMaxRangeVisualId")]
        public string UIMaxRangeVisualId { get; set; }

        [JsonProperty("RequiresMass")]
        public int RequiresMass { get; set; }

        [JsonProperty("MuzzleVelocityRandom")]
        public double MuzzleVelocityRandom { get; set; }

        [JsonProperty("MuzzleVelocityReduceDistance")]
        public int MuzzleVelocityReduceDistance { get; set; }

        [JsonProperty("DummyWeapon")]
        public bool DummyWeapon { get; set; }

        [JsonProperty("MinRadius")]
        public double MinRadius { get; set; }

        [JsonProperty("CountedProjectile")]
        public bool CountedProjectile { get; set; }

        [JsonProperty("TargetType")]
        public string TargetType { get; set; }

        [JsonProperty("NeedPrep")]
        public bool NeedPrep { get; set; }

        [JsonProperty("MuzzleVelocity")]
        public double MuzzleVelocity { get; set; }

        [JsonProperty("AimsStraightOnDisable")]
        public bool AimsStraightOnDisable { get; set; }

        [JsonProperty("NeedToComputeBombDrop")]
        public bool NeedToComputeBombDrop { get; set; }

        [JsonProperty("OverChargeWeapon")]
        public bool OverChargeWeapon { get; set; }

        [JsonProperty("PrefersPrimaryWeaponTarget")]
        public bool PrefersPrimaryWeaponTarget { get; set; }

        [JsonProperty("ProjectileLifetime")]
        public double ProjectileLifetime { get; set; }

        [JsonProperty("BallisticArc")]
        public string BallisticArc { get; set; }

        [JsonProperty("TargetRestrictOnlyAllow")]
        public string TargetRestrictOnlyAllow { get; set; }

        [JsonProperty("BelowWaterTargetsOnly")]
        public bool BelowWaterTargetsOnly { get; set; }

        [JsonProperty("ProjectileLifetimeUsesMultiplier")]
        public double ProjectileLifetimeUsesMultiplier { get; set; }

        [JsonProperty("RateOfFire")]
        public double RateOfFire { get; set; }

        [JsonProperty("ReTargetOnMiss")]
        public bool ReTargetOnMiss { get; set; }

        [JsonProperty("RequiresEnergy")]
        public int RequiresEnergy { get; set; }

        [JsonProperty("SlavedToBody")]
        public bool SlavedToBody { get; set; }

        [JsonProperty("ProjectileId")]
        public string ProjectileId { get; set; }

        [JsonProperty("YawOnlyOnTarget")]
        public bool YawOnlyOnTarget { get; set; }

        [JsonProperty("HeadingArcRange")]
        public int HeadingArcRange { get; set; }

        [JsonProperty("UIMinRangeVisualId")]
        public string UIMinRangeVisualId { get; set; }

        [JsonProperty("StopOnPrimaryWeaponBusy")]
        public bool StopOnPrimaryWeaponBusy { get; set; }

        [JsonProperty("SlavedToBodyArcRange")]
        public int SlavedToBodyArcRange { get; set; }

        [JsonProperty("IgnoresAlly")]
        public bool IgnoresAlly { get; set; }

        [JsonProperty("AboveWaterTargetsOnly")]
        public bool AboveWaterTargetsOnly { get; set; }

        [JsonProperty("TrackingRadius")]
        public double TrackingRadius { get; set; }

        [JsonProperty("Turreted")]
        public bool Turreted { get; set; }

        [JsonProperty("Damage")]
        public double Damage { get; set; }

        [JsonProperty("RackReloadTimeout")]
        public int? RackReloadTimeout { get; set; }

        [JsonProperty("ProjectilesPerOnFire")]
        public int? ProjectilesPerOnFire { get; set; }

        [JsonProperty("RackRecoilDistance")]
        public double? RackRecoilDistance { get; set; }

        [JsonProperty("TurretPitch")]
        public int? TurretPitch { get; set; }

        [JsonProperty("TurretPitchSpeed")]
        public int? TurretPitchSpeed { get; set; }

        [JsonProperty("TurretBoneYaw")]
        public string TurretBoneYaw { get; set; }

        [JsonProperty("RackSalvoSize")]
        public int? RackSalvoSize { get; set; }

        [JsonProperty("RackSlavedToTurret")]
        public bool? RackSlavedToTurret { get; set; }

        [JsonProperty("RackSalvoReloadTime")]
        public double? RackSalvoReloadTime { get; set; }

        [JsonProperty("MuzzleSalvoSize")]
        public int? MuzzleSalvoSize { get; set; }

        [JsonProperty("MuzzleSalvoDelay")]
        public double? MuzzleSalvoDelay { get; set; }

        [JsonProperty("ChargeDelay")]
        public double? ChargeDelay { get; set; }

        [JsonProperty("MuzzleChargeDelay")]
        public double? MuzzleChargeDelay { get; set; }

        [JsonProperty("TurretYawRange")]
        public int? TurretYawRange { get; set; }

        [JsonProperty("CollideFriendly")]
        public bool? CollideFriendly { get; set; }

        [JsonProperty("TargetPriorities")]
        public IList<string> TargetPriorities { get; set; }

        [JsonProperty("RackBones")]
        public IList<RackBone> RackBones { get; set; }

        [JsonProperty("Audio")]
        public Audio2 Audio { get; set; }

        [JsonProperty("RackFireTogether")]
        public bool? RackFireTogether { get; set; }

        [JsonProperty("TurretPitchRange")]
        public int? TurretPitchRange { get; set; }

        [JsonProperty("TurretYawSpeed")]
        public int? TurretYawSpeed { get; set; }

        [JsonProperty("TurretYaw")]
        public int? TurretYaw { get; set; }

        [JsonProperty("RackSalvoChargeTime")]
        public double? RackSalvoChargeTime { get; set; }

        [JsonProperty("TurretBoneMuzzle")]
        public string TurretBoneMuzzle { get; set; }

        [JsonProperty("FireTargetLayerCapsTable")]
        public FireTargetLayerCapsTable FireTargetLayerCapsTable { get; set; }

        [JsonProperty("TurretDualManipulators")]
        public bool? TurretDualManipulators { get; set; }

        [JsonProperty("TurretBonePitch")]
        public string TurretBonePitch { get; set; }

        [JsonProperty("EnergyChargeForFirstShot")]
        public bool? EnergyChargeForFirstShot { get; set; }

        [JsonProperty("WeaponRepackTimeout")]
        public double? WeaponRepackTimeout { get; set; }

        [JsonProperty("EnergyDrainPerSecond")]
        public int? EnergyDrainPerSecond { get; set; }

        [JsonProperty("WeaponUnpacks")]
        public bool? WeaponUnpacks { get; set; }

        [JsonProperty("EnergyRequired")]
        public int? EnergyRequired { get; set; }

        [JsonProperty("FireOnDeath")]
        public bool? FireOnDeath { get; set; }

        [JsonProperty("ForceSingleFire")]
        public bool? ForceSingleFire { get; set; }

        [JsonProperty("InitialProjectileStorage")]
        public int? InitialProjectileStorage { get; set; }

        [JsonProperty("WeaponUnpackAnimationRate")]
        public double? WeaponUnpackAnimationRate { get; set; }

        [JsonProperty("WeaponUnpackAnimation")]
        public string WeaponUnpackAnimation { get; set; }

        [JsonProperty("ArtilleryShieldBlocks")]
        public bool? ArtilleryShieldBlocks { get; set; }

        [JsonProperty("Buffs")]
        public IList<Buff> Buffs { get; set; }

        [JsonProperty("InitialDamage")]
        public double? InitialDamage { get; set; }

        [JsonProperty("DoTTime")]
        public double? DoTTime { get; set; }

        [JsonProperty("DoTPulses")]
        public int? DoTPulses { get; set; }

        [JsonProperty("RackRecoilReturnSpeed")]
        public int? RackRecoilReturnSpeed { get; set; }

        [JsonProperty("DetonatesAtTargetHeight")]
        public bool? DetonatesAtTargetHeight { get; set; }

        [JsonProperty("NukeOuterRingTicks")]
        public int? NukeOuterRingTicks { get; set; }

        [JsonProperty("NukeInnerRingTotalTime")]
        public int? NukeInnerRingTotalTime { get; set; }

        [JsonProperty("NukeInnerRingDamage")]
        public int? NukeInnerRingDamage { get; set; }

        [JsonProperty("NukeOuterRingRadius")]
        public int? NukeOuterRingRadius { get; set; }

        [JsonProperty("NukeOuterRingTotalTime")]
        public int? NukeOuterRingTotalTime { get; set; }

        [JsonProperty("NukeOuterRingDamage")]
        public int? NukeOuterRingDamage { get; set; }

        [JsonProperty("NukeInnerRingTicks")]
        public int? NukeInnerRingTicks { get; set; }

        [JsonProperty("NukeInnerRingRadius")]
        public int? NukeInnerRingRadius { get; set; }

        [JsonProperty("BeamLifetime")]
        public double? BeamLifetime { get; set; }

        [JsonProperty("BeamCollisionDelay")]
        public double? BeamCollisionDelay { get; set; }

        [JsonProperty("EnabledByEnhancement")]
        public string EnabledByEnhancement { get; set; }

        [JsonProperty("RenderFireClock")]
        public bool? RenderFireClock { get; set; }

        [JsonProperty("RackSalvoFiresAfterCharge")]
        public bool? RackSalvoFiresAfterCharge { get; set; }

        [JsonProperty("TurretBoneDualMuzzle")]
        public string TurretBoneDualMuzzle { get; set; }

        [JsonProperty("TurretBoneDualPitch")]
        public string TurretBoneDualPitch { get; set; }

        [JsonProperty("NotExclusive")]
        public bool? NotExclusive { get; set; }

        [JsonProperty("SalvoSize")]
        public int? SalvoSize { get; set; }

        [JsonProperty("Accurate")]
        public bool? Accurate { get; set; }

        [JsonProperty("DoNotCollideList")]
        public IList<string> DoNotCollideList { get; set; }

        [JsonProperty("FixBombTrajectory")]
        public bool? FixBombTrajectory { get; set; }

        [JsonProperty("BarrelLoop")]
        public BarrelLoop BarrelLoop { get; set; }

        [JsonProperty("MuzzleSalvoChargeDelay")]
        public int? MuzzleSalvoChargeDelay { get; set; }

        [JsonProperty("BarrelStart")]
        public BarrelStart BarrelStart { get; set; }

        [JsonProperty("MuzzleChargeStart")]
        public MuzzleChargeStart MuzzleChargeStart { get; set; }

        [JsonProperty("FixBombTrajectoryFirstRun")]
        public bool? FixBombTrajectoryFirstRun { get; set; }

        [JsonProperty("SkipReadyState")]
        public bool? SkipReadyState { get; set; }

        [JsonProperty("AnimationReload")]
        public string AnimationReload { get; set; }

        [JsonProperty("FiringRandomnessWhileMoving")]
        public double? FiringRandomnessWhileMoving { get; set; }

        [JsonProperty("DepthCharge")]
        public DepthCharge DepthCharge { get; set; }

        [JsonProperty("SalvoShotDelay")]
        public double? SalvoShotDelay { get; set; }

        [JsonProperty("CameraLifetime")]
        public int? CameraLifetime { get; set; }

        [JsonProperty("CameraVisionRadius")]
        public int? CameraVisionRadius { get; set; }

        [JsonProperty("CameraShakeMax")]
        public int? CameraShakeMax { get; set; }

        [JsonProperty("ShieldDamage")]
        public int? ShieldDamage { get; set; }

        [JsonProperty("CameraShakeDuration")]
        public double? CameraShakeDuration { get; set; }

        [JsonProperty("CameraShakeMin")]
        public int? CameraShakeMin { get; set; }

        [JsonProperty("CameraShakeRadius")]
        public int? CameraShakeRadius { get; set; }

        [JsonProperty("FireOnSelfDestruct")]
        public bool? FireOnSelfDestruct { get; set; }

        [JsonProperty("CanFireFromTransport")]
        public bool? CanFireFromTransport { get; set; }

        [JsonProperty("ToggleWeapon")]
        public string ToggleWeapon { get; set; }

        [JsonProperty("NoPause")]
        public bool? NoPause { get; set; }

        [JsonProperty("MuzzleVelocityRandomness")]
        public double? MuzzleVelocityRandomness { get; set; }

        [JsonProperty("WeaponUnpackLocksMotion")]
        public bool? WeaponUnpackLocksMotion { get; set; }

        [JsonProperty("ContinuousBeam")]
        public bool? ContinuousBeam { get; set; }

        [JsonProperty("RequireTime")]
        public int? RequireTime { get; set; }

        [JsonProperty("WeaponUnpackTimeout")]
        public int? WeaponUnpackTimeout { get; set; }

        [JsonProperty("WeaponUnpackAnimatorPrecedence")]
        public int? WeaponUnpackAnimatorPrecedence { get; set; }

        [JsonProperty("AnimationOpen")]
        public string AnimationOpen { get; set; }

        [JsonProperty("Flare")]
        public Flare Flare { get; set; }

        [JsonProperty("PreferPrimaryWeaponTarget")]
        public bool? PreferPrimaryWeaponTarget { get; set; }

        [JsonProperty("BallicsticArc")]
        public string BallicsticArc { get; set; }

        [JsonProperty("MuzzleSpecial")]
        public string MuzzleSpecial { get; set; }

        [JsonProperty("Display")]
        public string Display { get; set; }

        [JsonProperty("DamageToShields")]
        public int? DamageToShields { get; set; }

        [JsonProperty("AimControlPrecedence")]
        public int? AimControlPrecedence { get; set; }
    }

}
