// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FATBox.Core.ModCatalog
{

    public class WreckageLayers
    {

        [JsonProperty("Water")]
        public bool Water { get; set; }

        [JsonProperty("Land")]
        public bool Land { get; set; }

        [JsonProperty("Seabed")]
        public bool Seabed { get; set; }

        [JsonProperty("Sub")]
        public bool Sub { get; set; }

        [JsonProperty("Air")]
        public bool Air { get; set; }
    }

}
